server:
  port: 80
  auth:
    jwt-secret-key: "U@A@V#cAFbFWU#aNesMVp9x#v`rSocT4eni@&WAp2ihgnv^`rMCQkYVQ~Zt~w`Rs"
spring:
  profiles:
    active: @profile@
  datasource:
    url: jdbc:postgresql://localhost:5432/fastmirror
    username: postgres
    password: qzwxsaedc
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
