name: CI Manual
on:
  workflow_dispatch:
    inputs:
      publish:
        description: is release publish
        required: true
        type: choice
        options:
          - release
          - pre-release
        default: release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ github.event.inputs.version-suffix != 'release' }}
          draft: false
      - name: Upload Assets
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/FastMirrorServer-${{ github.ref }}-release.jar
          asset_name: FastMirrorServer.jar
          asset_content_type: application/jar
